import smtplib
import string
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)


GPIO.setup(20,GPIO.IN)
GPIO.setup(21,GPIO.IN)
HOST = "smtp.gmail.com"
SUBJECT = "Emergency Alert"
TO = "sachin.gawade@capgemini.com ; chirag.giri@capgemini.com"
FROM = "<insuredbuddy@gmail.com>On Behalf of Insured Buddy"
text = "Sensor from Vehicle number MH12EC7692 observed a jerk of noticable Manginute,owner name is scott Davis,Contact number is +919688797900 and location co-ordinates are 18.596277,73.692253.This is Autogenerated mail.Do not reply to this mail. "
BODY = string.join(("from: %s" %FROM, "to: %s" %TO,"Subject: %s" %SUBJECT, "     ", text), "\r\n")
while 1:
 if(GPIO.input(20) == True & GPIO.input(21) == True):
    s = smtplib.SMTP("smtp.gmail.com",587)
    s.set_debuglevel(1)
    s.ehlo()
    s.starttls()
    s.login("****@gmail.com", "********")
    s.sendmail(FROM,[TO],BODY)
    